version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - /bin/bash
      - '-c'
      - sleep 1d
#      - service supervisor start && supervisorctl stop docker_test && sleep 1d
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    build: db
    env_file: .env
    volumes:
      - '${DOCKER_PROJ_PATH}/db/psql:/var/lib/postgresql/data/'
#      - ./db/postgresql:/var/lib/postgresql/data/
    restart: always
