# Generated by Django 3.1.5 on 2021-01-27 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Валюта')),
                ('value', models.FloatField(verbose_name='Курс')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='CurrencyUSD',
            fields=[
                ('basecurrency_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_telegram_currency.basecurrency')),
            ],
            options={
                'verbose_name': 'Валюта USD',
                'verbose_name_plural': 'Валюты USD',
            },
            bases=('django_telegram_currency.basecurrency',),
        ),
    ]
