# Generated by Django 3.1.5 on 2021-02-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveSmallIntegerField(choices=[(0, 'Undefined'), (10, 'USD'), (20, 'EUR')], default=0, verbose_name='Валюта')),
                ('value', models.FloatField(verbose_name='Курс')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
    ]
